### ISSUE TITLE
Invalid driver dylib generated since #2170

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/MoltenVK#2186]
Checking out 9082ca839f4eb83d183837fe656059ac12e4ee03, which is the last commit before the merge of #2170, and building the dylib with `make macos` my application runs just as it used to.

Now if I checkout eff757144614a20d7b452c8388019783d9511a25 (from #2170), build the driver with `make macos` I get this output:
```
install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/sean/Documents/git/spnda/MoltenVK/Package/Release/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib (for architecture x86_64)
install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/sean/Documents/git/spnda/MoltenVK/Package/Release/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib (for architecture arm64)
...
note: Run script build phase 'Package MoltenVK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'MoltenVK-macOS' from project 'MoltenVKPackaging')
```
After changing the symlink to the new dylib location the application crashes with an EXC_BAD_ACCESS while loading the dylib file and this reason:
```
Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page
```

If I update past #2175, build it and run my application, instead of an application crash I now get this output (running with `VK_LOADER_DEBUG=error,warn,info`:
```
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/local/lib/libMoltenVK.dylib failed.
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/local/lib/libMoltenVK.dylib failed.
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/local/lib/libMoltenVK.dylib failed.
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/local/lib/libMoltenVK.dylib failed.
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/local/lib/libMoltenVK.dylib failed.
INFO:              Portability enumeration bit was set, enumerating portability drivers.
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/local/lib/libMoltenVK.dylib failed.
ERROR | DRIVER:    vkCreateInstance: Found no drivers!
```

The rest of my setup did not change and switching to any of the commits always gives the same exact result. I also can't find the section of the documentation anymore that talked about symlinking the dylib file from `/usr/local/lib` to the build output directly when developing, so did that perhaps change?

**Comment by spnda** [comment]
Hmm, interesting find about the size of the file, which I can confirm. I just checked out the latest again and compiled it and got a 86KB dylib instead of the 15.2MB one. And I can confirm that doing `make clean && make macos` then produces the 15.2MB dylib file again. Btw I am on Xcode 15.3.

**Comment by richard-lunarg** [comment]
>>This is unfortunate, as it breaks compatiblity with Vulkan SDK structure and thus application cmake 
>>scripts also break when doing development with local MoltenVK builds, i.e. you can no longer just 
>>change the VULKAN_SDK env variable to point at your local MVK build. You have to either change your 
>>cmake script, or manually create a symlink at MoltenVK/Package/Release/MoltenVK/dylib.

FWIW, the next SDK is using v1.2.8 (which will be out next week). Vulkan-Tools cmake files have also been updated to reflect the new location of the .dylib.

**Comment by SRSaunders** [comment]
Hi @richard-lunarg, will cmake’s existing FindVulkan.cmake continue to work with this change?  Many cross platform apps depend on this working.  Also, is this change universal for all SDK platforms or just for MoltenVK?

**Comment by richard-lunarg** [comment]
libMoltenVK.dylib will be in the same place in the SDK for quite some time moving forward. It's just moved in the MoltenVK build artifacts.

**Comment by billhollings** [comment]
> `install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/sean/Documents/git/spnda/MoltenVK/Package/Release/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib (for architecture x86_64)`

> I just checked out the latest again and compiled it and got a 86KB dylib instead of the 15.2MB one.

These should be fixed in PR #2175. Try running from the SDK release [v.1.2.8](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.8) tag.

**Comment by SRSaunders** [comment]
1. Checkout out 1d98babb721c03667f65e7f6197ca2a356d19198
2. ./fetchDependencies --macos
3. Launch MoltenVKPackaging.xcodeproj
4. Build --> successful 15.2 MB build at MoltenVK/Package/Release/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib
5. Change something trivial (e.g. `#define MVK_HIDE_VULKAN_SYMBOLS 1`)
6. Build --> build completes, but generates a non-functional dylib of 101 KB in size.
7. Build clean
8. Build --> successful 15.2 MB build

I'm not sure, but perhaps incremental builds are not linking in some missing pieces.  Kind of annoying since you have to build clean and rebuild with every change to get a functional dylib.

**Comment by spnda** [comment]
> > `install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/sean/Documents/git/spnda/MoltenVK/Package/Release/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib (for architecture x86_64)`
> 
> 
> 
> and
> 
> 
> 
> > I just checked out the latest again and compiled it and got a 86KB dylib instead of the 15.2MB one.
> 
> 
> 
> These should be fixed in PR #2175. Try running from the SDK release [v.1.2.8](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.8) tag.

As stated in the original comment, I tested past #2175, which fixed the first issue, but was the one which brought up the issue with the tiny binary which contains no Vulkan symbols. So, no, that PR did not fix the second issue.

**Comment by billhollings** [comment]
PR #2196 should fix this. Please retest with latest, and close this issue if the problem has been fixed.
