### ISSUE TITLE
Crash if more than 2 GPU devices are connected

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#875]
MoltenVK crashes in our application when more than 2 GPUs are connected to the system. E.g. we have a Macbook Pro with an integrated and dedicated GPU and we also connected an external eGPU.

The error seems to be connected to the following line in MVKInstance.h

`MVKVectorInline<MVKPhysicalDevice, 2> _physicalDevices;`

When changing this to either
`MVKVectorInline<MVKPhysicalDevice, 4> _physicalDevices;`
or
`MVKVectorDefault<MVKPhysicalDevice> _physicalDevices;`

our application works fine again.

As I have introduced this special vector type, I wonder what is wrong. I can't see any issues with the implementation. However I found a smaller bug in MVKVectorAllocator.h but fixing this does not fix the crash.

As the implementation has been changed quite a bit compared to my initial implementation, I wonder if somebody who did the changes might have a look at this?

You can trigger this bug easily by simply populating _physicalDevices with 3 devices, e.g. duplicate some devices.

**Comment by billhollings** [comment]
@aerofly 

This is fixed in PR #889. Please retest and close if this fixes your issue.

The problem arose from an earlier change to store `MVKPhysicalDevice` instances instead of their pointers (using `emplace_back()`), in an effort to avoid unnecessary invocations of `new`. Adding the third `MVKPhysicalDevice` to the `MVKVectorInline` (now `MVKSmallVector`) triggered the expected internal re-allocation, which caused a crash when the contained `MVKPhysicalDevice` instances were moved through construction/destruction.

I've reverted back to tracking `MVKPhysicalDevices` as pointers, and reviewed other uses of `emplace_back()` in MoltenVK.

**Comment by aerofly** [comment]
@billhollings 
Thank you for looking into and fixing this issue. As far as I can see, this is now fixed and works when using more than the 2 preallocated devices. Again, it's a very rare case only.

I still don't see why it did crash though? For it to work properly we should probably implement a proper move or copy constructor for MVKPhysicalDevice when being used in a MVKSmallVector. The problematic field in MVKPhysicalDevice `id<MTLDevice> _mtlDevice` did cause the actual crash.

Also thank you for modifying MoltenVK to avoid the extra allocations while submitting data to the queue. We hardly observe any allocations/deallocations now while using MoltenVK. A big improvement over previous versions.

**Comment by billhollings** [comment]
> we should probably implement a proper move or copy constructor for MVKPhysicalDevice

I looked into this idea when trying to fix the issue, and decided not to bother:

- `MVKPhysicalDevice` is a large, internally complicated object, not particularly conducive to moving and copying.
- They are allocated once at startup, and hang out only in the `MVKInstance`, so never normally need to be moved around. 
- Each instance is 34kb in size. With 2 pre-allocated in the `MVKSmallVector`, it leaves a lot of memory unused in the vector if either 1 or 3+ instances are added (anything but 2 GPU's).

**Comment by billhollings** [comment]
BTW...if this is fixed now, please close this issue.

**Comment by billhollings** [comment]
>Also thank you for modifying MoltenVK to avoid the extra allocations while submitting data to the queue. We hardly observe any allocations/deallocations now while using MoltenVK. A big improvement over previous versions.

Glad it helped!

**Comment by aerofly** [comment]
Thank you for your commenting on this. Issue is fixed.
