### ISSUE TITLE
MoltenVK says I can use D24_UNNORM_S8 then says I can't.

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/MoltenVK#888]
When creating the depth buffer for my app, I first use vkGetPhysicalDeviceFormatProperties to check if a format meets my depth buffer requirement then I use vkGetPhysicalDeviceFormatProperties to see if I can use it as a depth stencil attachment with optimal tiling.  For D24_UNORM_S8 it says I can but when I create an image using it I first get a warning from the validation layers saying "format is not supported for this combination of parameters" then a message from MoltenVK saying "[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_D24_UNORM_S8_UINT is not supported on this device. Using VkFormat VK_FORMAT_D32_SFLOAT_S8_UINT instead."

1. It seems the validation layer has figured out it is not supported. What do I need to do to figure that out?

2. If the MoltenVK message is accurate and the format is simply not supported, why did vkGetPhysicalDeviceFormatProperties tell me it could be used for depth stencil?

I had no warnings when running with VulkanSDK 1.1.85.0. I switched to 1.2.135.0 and this problem emerged.

Here is my code for finding a supported depth format.

```
bool
VulkanAppSDL::getSupportedDepthFormat(vk::PhysicalDevice gpu,
                                      stencilRequirement requiredStencil,
                                      depthRequirement requiredDepth,
                                      vk::Format& depthFormat,
                                      vk::ImageAspectFlags& aspectMask)
{
    struct depthFormatDescriptor {
        stencilRequirement stencil;
        depthRequirement depth;
        vk::Format vkformat;
    };
    std::vector<depthFormatDescriptor> depthFormats = {
      { eNoStencil, e16bits, vk::Format::eD16Unorm },
      { eStencil, e16bits, vk::Format::eD16UnormS8Uint },
      { eStencil, e24bits, vk::Format::eD24UnormS8Uint },
      { eNoStencil, e32bits, vk::Format::eD32Sfloat },
      { eStencil, e32bits, vk::Format::eD32SfloatS8Uint }
    };

    for (auto& format : depthFormats)
    {
        if (format.depth >= requiredDepth
            && format.stencil >= requiredStencil) {
            vk::FormatProperties formatProps;
            gpu.getFormatProperties(format.vkformat, &formatProps);
            // Format must support depth stencil attachment for optimal tiling
            if (formatProps.optimalTilingFeatures & vk::FormatFeatureFlagBits::eDepthStencilAttachment) {
                depthFormat = format.vkformat;
                if (format.stencil == eStencil)
                    aspectMask = vk::ImageAspectFlagBits::eDepth | vk::ImageAspectFlagBits::eStencil;
                else
                    aspectMask = vk::ImageAspectFlagBits::eDepth;
                return true;
            }
        }
    }
    return false;
```

And here is the code that calls it and creates an image of the returned format to use for the depth buffer.

```    if (!getSupportedDepthFormat(vkctx.gpu, eNoStencil, e24bits,
                                 depthFormat, aspectMask))
      return false;
    vkctx.depthBuffer.format = static_cast<VkFormat>(depthFormat);

    VkImageCreateInfo image = {};
    image.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    image.pNext = NULL;
    image.imageType = VK_IMAGE_TYPE_2D;
    image.format = static_cast<VkFormat>(depthFormat);
    image.extent.width = w_width;
    image.extent.height = w_height;
    image.extent.depth = 1;
    image.mipLevels = 1;
    image.arrayLayers = 1;
    image.samples = VK_SAMPLE_COUNT_1_BIT;
    image.tiling = VK_IMAGE_TILING_OPTIMAL;
    image.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
                            | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
    image.flags = 0;

    VkMemoryRequirements mem_reqs;
    VkResult U_ASSERT_ONLY err;
    bool U_ASSERT_ONLY pass;

    /* create image */
    err = vkCreateImage(vkctx.device, &image, NULL, &vkctx.depthBuffer.image);
    assert(!err);
```

**Comment by cdavis5e** [comment]
I take it you're on AMD hardware. It's common for AMD GPUs not to support that format.

> "format is not supported for this combination of parameters"
This is a huge clue. The validation layers are using `vkGetPhysicalDeviceImageFormatProperties()` (notice the "Image") to validate the parameters you passed. That function says you can't create an image of the desired format, type, and usage. The fallback is in place in case some app tries to use `D24_UNORM_S8_UINT` without checking if it's supported. Apparently, it used to do this silently; now it complains loudly.

I think we need to fix up `vkGetPhysicalDeviceFormatProperties()` to report no format features when the device doesn't support that format.

**Comment by MarkCallow** [comment]
I just found another similar case. In 1.1.85.0, the following code would tell me that BC2_UNORM is not supported on iOS. In 1.2.135.0 it tells me it is,  so I go ahead and try to upload to Vulkan only for vkGetPhysicalDeviceImageFormatProperties to tell me no you can't do that, which of course is true. Why did this code say okay?

```
    vk::Format vkFormat
                = static_cast<vk::Format>(ktxTexture_GetVkFormat(kTexture));
    vk::FormatProperties properties;
    vkctx.gpu.getFormatProperties(vkFormat, &properties);
    vk::FormatFeatureFlags& features =  tiling == vk::ImageTiling::eLinear ?
                                        properties.linearTilingFeatures :
                                        properties.optimalTilingFeatures;
    vk::FormatFeatureFlags wantedFeatures =
             vk::FormatFeatureFlagBits::eSampledImage
           | vk::FormatFeatureFlagBits::eSampledImageFilterLinear;
    if (!(features & wantedFeatures)) {
        ktxTexture_Destroy(kTexture);
        throw unsupported_ttype();
    }

```

**Comment by MarkCallow** [comment]
> I take it you're on AMD hardware. It's common for AMD GPUs not to support that format.

No. I'm on Intel hardware for that case.

So I should use ImageFormatProperties? Does it provide a superset of the information given by FormatProperties?

**Comment by MarkCallow** [comment]
>    "format is not supported for this combination of parameters"
>
>This is a huge clue. 

Not to me. The language of the message says to me that the format is supported to some degree, just not for the combination of parameters I was using. Of course my judgement was clouded by thinking the format was supported for depth-stencil given the result of the FormatProperties call.

**Comment by MarkCallow** [comment]
> Apparently, it used to do this silently; now it complains loudly.

No. I remember now. It has always complained. That was what prompted me to add the code for selecting a supported depth buffer format back when I first used MoltenVK, a long, long time ago. Something has changed in VkPhysicalDeviceGetFormatProperties.  It used to correctly inform that these formats were not supported but now it does not.

**Comment by billhollings** [comment]
I've confirmed there is a problem with how the properties of unsupported formats are returned. Working on it.

**Comment by billhollings** [comment]
@MarkCallow 

This is fixed in PR #891. Please retest and close this issue if it fixes the issues you encountered.

**Comment by danginsburg** [comment]
It seems to work fine but why does MoltenVK have to print this out on every startup?  Is there really an error happening here?

[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_D16_UNORM_S8_UINT is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_D16_UNORM_S8_UINT is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_EAC_R11_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_EAC_R11_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_EAC_R11G11_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_EAC_R11G11_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_EAC_R11_UNORM_BLOCK is not supported on this device.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_EAC_R11G11_UNORM_BLOCK is not supported on this device.

**Comment by MarkCallow** [comment]
Thank you for the rapid fix. Unfortunately I'm not set up to build MoltenVK so it is hard for me to test. I am using Vulkan SDKs so I hope it won't be long before there is a new SDK that incorporates this fix preferably also with the debugging macro you apparently left set  (c/f @danginsburg's comment) unset again.

**Comment by MarkCallow** [comment]
If this PR is in Vulkan SDK 1.2.141.0, it does not fix the problem. VkGetPhysicalDeviceFormatProperties is still reporting that `VK_FORMAT_D24_UNORM_S8_UINT` can be used.

**Comment by billhollings** [comment]
> VkGetPhysicalDeviceFormatProperties is still reporting that `VK_FORMAT_D24_UNORM_S8_UINT` can be used.

Oops. This was because `VK_FORMAT_D24_UNORM_S8_UINT` is one of the few formats that MoltenVK permits automatic substitution, and MoltenVK was not properly setting properties for those substitutable formats.

This is now fixed in PR #910.
